[package]
name = "ject"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rustc-hash = "1.1"
smallvec = "1.10"
rustyline = "12.0"
serde_json = "1.0"
colored = "2.0"
